version: '3.8'
services:
  redpanda:
    image: redpandadata/redpanda:v23.3.5
    container_name: redpanda-broker
    command:
      - redpanda start
      - --smp 1
      - --memory 1G
      - --overprovisioned
      - --reserve-memory 0M
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr internal://redpanda:9092,external://localhost:19092
    ports:
      - "18081:18081"
      - "18082:18082"
      - "19092:19092"
      - "19644:9644"
    volumes:
      - redpanda-data:/var/lib/redpanda/data
    environment:
      - REDPANDA_AUTO_CREATE_TOPICS_ENABLED=true
    healthcheck:
      test: ["CMD-SHELL", "rpk cluster health | grep -E 'Healthy:.+true' || exit 1"]
      interval: 15s
      timeout: 3s
      retries: 5
      start_period: 30s

  redpanda-console:
    image: redpandadata/console:latest
    container_name: redpanda-console
    depends_on:
      redpanda:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - KAFKA_BROKERS=redpanda:9092
      - KAFKA_SCHEMAREGISTRY_ENABLED=true
      - KAFKA_SCHEMAREGISTRY_URLS=http://redpanda:8081

volumes:
  redpanda-data:
